apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: production-app-pdb
  namespace: {{ .Values.namespace }}

spec:
  minAvailable: 2

  selector:
    matchLabels:
      app: production-app
